/* service-worker.js — precache-everything, cache-first. Offline 100%.
   NOTE: the PRECACHE list + VERSION are generated by tools/gen-precache.py.
   After editing any asset, re-run that tool (it bumps VERSION) so caches refresh. */
const VERSION = '79710d909f';
const CACHE = 'tj-' + VERSION;
const PRECACHE = [
  './',
  '404.html',
  'assets/icons/apple-touch-icon-180.png',
  'assets/icons/icon-192.png',
  'assets/icons/icon-512.png',
  'assets/img/003ed1488a480ecb.webp',
  'assets/img/0320ae3d743e9ebe.webp',
  'assets/img/05d75969da01ea95.webp',
  'assets/img/10aff0eb52dfe9b2.webp',
  'assets/img/18425fd676183545.webp',
  'assets/img/1c8c930e03e02efb.webp',
  'assets/img/1ce8c6f09d6e71c3.webp',
  'assets/img/2047d8f35fe27f41.webp',
  'assets/img/29b856652ab3b012.webp',
  'assets/img/2a63dad4d7695d9c.webp',
  'assets/img/3119e43038f60c65.webp',
  'assets/img/39386faae71d4f9a.webp',
  'assets/img/3a4483d1c0bafc76.webp',
  'assets/img/41a9149874b5eb09.webp',
  'assets/img/45eee2782b3cef15.webp',
  'assets/img/45f76ef1bb0c5ad9.webp',
  'assets/img/4c9b5aabfa0e709b.webp',
  'assets/img/4f831282bb619fdc.webp',
  'assets/img/5f9e1e9ea5675998.webp',
  'assets/img/6072d2462728b251.webp',
  'assets/img/60a4cd90dd7e59f1.webp',
  'assets/img/617758c3142c4605.webp',
  'assets/img/63d0acd4bcd51dec.webp',
  'assets/img/67aa5484216076fc.webp',
  'assets/img/6a5226021ab90ea2.webp',
  'assets/img/6a816b240a90f6be.webp',
  'assets/img/7fa31ad2091c88ce.webp',
  'assets/img/869d84e80cfe7e5e.webp',
  'assets/img/883b01174c5fd6be.webp',
  'assets/img/887007adf6a09f41.webp',
  'assets/img/8f80ec73bf1034fa.webp',
  'assets/img/9059c7f4f3450cae.webp',
  'assets/img/99fcecbd44d504d1.webp',
  'assets/img/9d0ba74ce45d8f8e.webp',
  'assets/img/a2311df9fa485f92.webp',
  'assets/img/a5f7bc0deba69316.webp',
  'assets/img/a7fef3e737e76122.webp',
  'assets/img/ab7346fdacca6cae.webp',
  'assets/img/af5b9f27ce8fe75e.webp',
  'assets/img/b4f03c2c1832946a.webp',
  'assets/img/ba526b7625cde719.webp',
  'assets/img/c4818923bbe364a5.webp',
  'assets/img/c60a336d8d3e1dde.webp',
  'assets/img/c826b5f1aabf55eb.webp',
  'assets/img/c8d3ed33e7a6f0be.webp',
  'assets/img/c8e5e6149abd8360.webp',
  'assets/img/caa996b277c67c86.webp',
  'assets/img/cb4382cba59ff3aa.webp',
  'assets/img/ce1d7daea4085b48.webp',
  'assets/img/d0e66127a0a4b3e7.webp',
  'assets/img/d512e42f9a9cc439.webp',
  'assets/img/d6ad180e1b7f5948.webp',
  'assets/img/dda58dd986c036cf.webp',
  'assets/img/e00884408ffbd595.webp',
  'assets/img/e0938c2545410f12.webp',
  'assets/img/e22edcf3110b6fad.webp',
  'assets/img/e238cd2d76d7b17e.webp',
  'assets/img/e41d58e43a74f2bf.webp',
  'assets/img/e5338f97f7dd9b94.webp',
  'assets/img/e817651f4667a23c.webp',
  'assets/img/ee50892c166c6467.webp',
  'assets/img/ee56d0daf475327c.webp',
  'assets/img/f70ece97ee1b0d09.webp',
  'assets/img/f8b0973207458d7b.webp',
  'assets/maps/tokyo-metro-1.png',
  'assets/maps/tokyo-metro-1.webp',
  'css/app.css',
  'css/reset.css',
  'data/checklist.json',
  'data/docs.json',
  'data/emergency.json',
  'data/exchange.json',
  'data/info.json',
  'data/itinerary.json',
  'data/medical.json',
  'data/musteat.json',
  'data/photospots.json',
  'data/phrases.json',
  'data/places.json',
  'data/restaurants.json',
  'data/shopping.json',
  'data/tips.json',
  'data/transit.json',
  'data/weather.json',
  'favicon-32.png',
  'index.html',
  'js/app.js',
  'js/data.js',
  'js/idb.js',
  'js/panzoom.js',
  'js/router.js',
  'js/screens.js',
  'js/util.js',
  'manifest.webmanifest',
  'offline.html',
];

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // add individually so one bad asset doesn't fail the whole install
    await Promise.allSettled(PRECACHE.map((u) => c.add(u)));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.req || e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return; // let cross-origin go to network
  e.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: false });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') {
        const clone = res.clone();
        const c = await caches.open(CACHE);
        c.put(req, clone);
      }
      return res;
    } catch (err) {
      if (req.mode === 'navigate') {
        return (await caches.match('index.html')) || (await caches.match('./')) || (await caches.match('offline.html')) || Response.error();
      }
      return Response.error();
    }
  })());
});

self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });
